### ISSUE TITLE
BUILD file not found in directory 'xds/data/orca/v3' of external repository @@com_github_cncf_xds_go. Add a BUILD file to a directory to mark it as a package.

### ISSUE THREAD

**Issue by jferrl** [cncf/xds#108]
We are using Bazel to build our repo: The version `v0.0.0-20240905190251-b4127c9b8d78` fails: 

`ERROR: no such package '@@com_github_cncf_xds_go//xds/data/orca/v3': BUILD file not found in directory 'xds/data/orca/v3' of external repository @@com_github_cncf_xds_go. Add a BUILD file to a directory to mark it as a package.`

Please, could you help me?

**Comment by adisuissa** [comment]
Hmmm... I do see https://github.com/cncf/xds/blob/main/xds/data/orca/v3/BUILD and it has been there since Oct 2021.
Can you please provide more details into what is failing?

**Comment by jferrl** [comment]
> Hmmm... I do see https://github.com/cncf/xds/blob/main/xds/data/orca/v3/BUILD and it has been there since Oct 2021. Can you please provide more details into what is failing?

Sorry. I fixed it using

```
go_repository(
        name = "com_github_cncf_xds_go",
        build_file_generation = "on",
        build_file_proto_mode = "disable",
        importpath = "github.com/cncf/xds/go",
        sum = "h1:QVw89YDxXxEe+l8gU8ETbOasdwEV+avkR75ZzsVV9WI=",
        version = "v0.0.0-20240905190251-b4127c9b8d78",
    )
```

**build_file_generation = "on"**

Using previous version of `github.com/cncf/xds/go` does not fail. I dont know why but using v`0.0.0-20240905190251-b4127c9b8d78` needs this config in bazel.
