### ISSUE TITLE
Need documentation

### ISSUE THREAD

**Issue by kyessenov** [cncf/xds#29]
Envoy is taking a dependency on protos from this repo. That means Envoy docs need references to the protos here in a better form than raw source code.

**Comment by kyessenov** [comment]
cc @markdroth @phlax 
Do you have any thoughts on how to publish the protos here? Do we have a website? I think the tooling in Envoy is probably good enough.

**Comment by mattklein123** [comment]
I think initially the way I would do this is:
1) Have Envoy be able to run protodoc, etc. on this repo.
2) Allow protodoc annotations in this repo.

This will allow this repo to look like any other protos to Envoy which should make it "just work."

If/when other clients want to generate docs from here we can introduce the concept of client specific doc tags.

**Comment by phlax** [comment]
and linting for unused imports!

**Comment by kyessenov** [comment]
@phlax can you help with 1)? Maybe some pointer how to make envoy CI produce HTML for protos here?

**Comment by markdroth** [comment]
Is there anything left to do here, or can this be closed?

**Comment by kyessenov** [comment]
I think the initial work is done. We probably need some CI to validate protodoc annotations, but that can be a separate issue.
