### ISSUE TITLE
Request to regenerate Go grpc bindings with newer version of the tool

### ISSUE THREAD

**Issue by easwars** [cncf/xds#41]
While looking at the generated `*.pb.go` files in this [repository](https://github.com/cncf/xds/tree/main/go), I figured that the generated code had been generated by an older version of the tool which generates Go bindings for grpc services. The latest version can be found [here](https://github.com/grpc/grpc-go/tree/master/cmd/protoc-gen-go-grpc).

Specifically, I'm talking about the generated functions which are used to register service handlers. For example, this one: https://github.com/cncf/xds/blob/1e77728a1eaa11d6c931ec2ccd6e95f516a7ef94/go/udpa/service/orca/v1/orca.pb.go#L264

As one can see, this function takes two inputs:
- the first one being a `*grpc.Server`, and
- the second one being the service handler which is to be registered.

Newer versions of the tool generate code which uses the [ServiceRegistrar](https://pkg.go.dev/google.golang.org/grpc#ServiceRegistrar) interface as its first input instead. For example, see [here](https://github.com/grpc/grpc-go/blob/584d9cd11a1da55e3558041c9f88f22ca2255f4e/health/grpc_health_v1/health_grpc.pb.go#L138). This is more flexible because it allows concrete types than a `*grpc.Server` on which the service handler is to be registered.

grpc-go provides a version of a gRPC server which uses xDS to get its configuration. You can find that [here](https://pkg.go.dev/google.golang.org/grpc@v1.47.0/xds#GRPCServer). For the grpc services contained in `*pb.go` files in this repository to be registered on the above mentioned xDS-enabled gRPC server, they need to be generated using newer versions of the `protoc-gen-go-grpc`.

**Comment by dfawley** [comment]
FWIW the newer version of `protoc-gen-go-grpc` is backward compatible with `protoc-gen-go`, but it does require setting an extra flag if you don't want it to require users to embed the `Unimplemented<ServiceName>Server` struct (which allows for service extensibility) in their implementations.

This is documented in the README: https://github.com/grpc/grpc-go/blob/master/cmd/protoc-gen-go-grpc/README.md#future-proofing-services

**Comment by easwars** [comment]
Looks like this has been taken care of.
