### ISSUE TITLE
Clarification on glob collections behavior

### ISSUE THREAD

**Issue by PapaCharlie** [cncf/xds#91]
Hello, I have a question on a specific aspect of glob collections. In the [definition for glob collections](https://github.com/cncf/xds/blob/8a4994d93e501495834ab448784a82bf365c94e7/proposals/TP1-xds-transport-next.md?plain=1#L399), the following is mentioned:

> Globs can exist in arbitrary path locations, e.g. `xdstp://some-authority/envoy.config.listener.v3.Listener/some/longer/path/*`. Multiple globs may be subscribed to in a DeltaDiscoveryRequest.

Does this mean that the following resource:
```
xdstp://some-authority/envoy.config.listener.v3.Listener/some/longer/path/resourceName
```
Belongs to each of these collections?
```
xdstp://some-authority/envoy.config.listener.v3.Listener/some/longer/path/*
xdstp://some-authority/envoy.config.listener.v3.Listener/some/longer/*
xdstp://some-authority/envoy.config.listener.v3.Listener/some/*
```

Or are glob collection URLs / resource URNs meant to be opaque, without actually implying hierarchy?

**Comment by markdroth** [comment]
Good question!

Considering this from first principles, my gut reaction is that just from a simplicity perspective, we should say that `xdstp://some-authority/envoy.config.listener.v3.Listener/some/longer/path/resourceName` belongs specifically to `xdstp://some-authority/envoy.config.listener.v3.Listener/some/longer/path/*` but not to `xdstp://some-authority/envoy.config.listener.v3.Listener/some/longer/*` or `xdstp://some-authority/envoy.config.listener.v3.Listener/some/*` -- i.e., it should not be recursive.  But I'd be open to the opposite semantic if we can convince ourselves that (a) there's a use-case that benefits from that semantic and (b) there are no cases where that semantic does any harm or introduces any ambiguity.

It's also worth checking how existing implementations actually behave.  @htuch @adisuissa, can you check how Envoy behaves in this case?  (gRPC currently does not support glob collections, so I think there's only one data point here.)

**Comment by shivamgupta1** [comment]
The way [LEDS design](https://docs.google.com/document/d/1aZ9ddX99BOWxmfiWZevSB5kzLAfH2TS8qQDcCBHcfSE/edit?usp=sharing) introduces endpoint globs like `xdstp://some-authority/envoy.config.endpoint.v3.LbEndpoint/cluster_0/locality_0/endpoint_0` makes it look like it would be helpful to have the URLs `xdstp://some-authority/envoy.config.endpoint.v3.LbEndpoint/cluster_0/*` and `xdstp://some-authority/envoy.config.endpoint.v3.LbEndpoint/cluster_0/locality_0/*` both be able to refer to the same globs. So if one client is interested in only `locality_0` endpoints, it gets those but if another client wants endpoints from all localities, that works seamlessly too without needing to store duplicate glob data. In terms of subscriptions and the directory structure, this would be similar to Zookeeper watches that are also recursive by nature. Does this introduce any ambiguity?

**Comment by adisuissa** [comment]
+1 to Mark's comment.
I think that non-recursive subscription is the right way to go here, and if a recursive subscription is intended it should be explicit (similar to python's glob of * vs **).

> The way [LEDS design](https://docs.google.com/document/d/1aZ9ddX99BOWxmfiWZevSB5kzLAfH2TS8qQDcCBHcfSE/edit?usp=sharing) introduces endpoint globs like `xdstp://some-authority/envoy.config.endpoint.v3.LbEndpoint/cluster_0/locality_0/endpoint_0` makes it look like it would be helpful to have the URLs `xdstp://some-authority/envoy.config.endpoint.v3.LbEndpoint/cluster_0/*` and `xdstp://some-authority/envoy.config.endpoint.v3.LbEndpoint/cluster_0/locality_0/*` both be able to refer to the same globs. So if one client is interested in only `locality_0` endpoints, it gets those but if another client wants endpoints from all localities, that works seamlessly too without needing to store duplicate glob data. In terms of subscriptions and the directory structure, this would be similar to Zookeeper watches that are also recursive by nature. Does this introduce any ambiguity?

From a resource-model perspective I don't think it will be useful, as the xDS-protocol is a pub-sub model where the subscription is explicit and (typically) associated with some other resource.
Say a cluster has a few localities (that are either statically defined, or received in an EDS message), and just a single mention of `xdstp://some-authority/envoy.config.endpoint.v3.LbEndpoint/cluster_0/*` in the cluster, how would the client know how to map the resources in the response to the correct locality?

I can see some benefit if one is looking at this from the message-exchange perspective, where a client aggregates subscriptions (and minimizing the number of resources in a request). I'm not sure if there's much added value here, but I guess it can be supported. If that is the intent, then I think an explicit support for recursion (e.g., **) will need to be added and both the client and server need to multiplex and demultiplex the requests/responses accordingly.
FWIW, Envoy should batch all the subscriptions into a single xDS-request that is sent to the server (multiple [resource_names_subscribe](https://github.com/envoyproxy/envoy/blob/d298fdc76bbb699401370cf786274f145c21b375/api/envoy/service/discovery/v3/discovery.proto#L209) entries), so I'm not sure if there's much benefit from going in that direction (though it may depend on the number of localities and other specifics).

**Comment by shivamgupta1** [comment]
> how would the client know how to map the resources in the response to the correct locality?

Because the actual resource URN would contain the locality, something like `xdstp://some-authority/envoy.config.endpoint.v3.LbEndpoint/cluster_0/locality_0/endpoint_0`? It would require the client to parse and interpret the URNs though. Or the info could be part of the metadata. The idea of explicit `**` looks good to me too.

Anyhow, me and @PapaCharlie were only interested to know the intended behavior. Thanks for the clarifications – the original doc seems ambiguous about this.

**Comment by markdroth** [comment]
Summarizing what I'm hearing so far:
- There are no examples of a case where the recursive behavior would be useful.  It would not work in LEDS due to having a separate resource locator for each locality.
- We seem to be agreeing that supporting recursion would add at least some complexity to implementations.

Sounds like consensus is that it should be non-recursive.

@adisuissa Can you confirm that this is how Envoy's implementation behaves?

**Comment by markdroth** [comment]
> Because the actual resource URN would contain the locality, something like `xdstp://some-authority/envoy.config.endpoint.v3.LbEndpoint/cluster_0/locality_0/endpoint_0`? It would require the client to parse and interpret the URNs though.

We generally try to keep a clean separation between the transport protocol layer and the data model layer, and I don't think we'd want to blur that line this way.  In principle, just as the transport protocol should treat the resource contents as opaque blobs, the data model layer should treat resource names as opaque blobs.  They're unique values but should not be interpretted for meaning.

**Comment by PapaCharlie** [comment]
Thanks for the discussion everyone! I think it's good to clarify all this. Defining a recursive glob collection seems like a fine idea, but definitely not necessary as of right now. I'm closing this issue now, and will open a PR to improve the language of the proposal to make this clear

**Comment by htuch** [comment]
>  If that is the intent, then I think an explicit support for recursion (e.g., **) will need to be added and both the client and server need to multiplex and demultiplex the requests/responses accordingly.

FWIW I'm in favor of explicit operator as suggested here if we do desire such semantics. It seems there is a reasonable case for both behaviors with the current behavior as described.
